## Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Expose the port your application runs on (default for Express is 3000)
EXPOSE 3000

# Set the default command to run your application
CMD ["npm", "start"]
